# HW 1.1


# QR Decomposition

QR decomposition, also known as a QR factorization or QU factorization, is a decomposition of a matrix A into a product A = QR of an orthonormal matrix Q and an upper triangular matrix R. QR decomposition is often used to solve the linear least squares problem and is the basis for a particular eigenvalue algorithm, the QR algorithm.

## Computing the QR decomposition

There are several methods for actually computing the QR decomposition, such as by means of the Gram–Schmidt process, Householder transformations, or Givens rotations. **In this homework, we will use Gram–Schmidt process to compute QR decomposition**

**Important: You will get extra score if you compute QR decomposition using another algorithm!**


In [1]:
from math import sqrt
import numpy as np

epsilon = 10e-5

## Gram–Schmidt process
Here is an overview of Gram-Schmidt process:
![GS](https://i.ibb.co/GdHsWpD/image.png)


### Compute $\hat{q}$ in `q_hat_calculate` function:

In [2]:
def q_hat_calculate(index, vector, vectors):
    """
    :param index: the i that we want to calculate q_hat for
    :param vector: the ith vector that we want to calculate q_hat for
    :param vectors: the previous q's that we calculated
    :return: q hat vector, vector R for QR decomposition
    """
    #### Your code here
    if not isinstance(vectors, np.ndarray):
        vectors = np.ndarray(vectors)
    
    q_hat = vector.copy()
    
    for q in vectors.T[:index, :]:
        q_hat -= np.dot(q, vector) * q
        
    return q_hat

### Implement Gram-Schmidt algorithm:

In [3]:
def gram_schmidt_algorithm(vectors):
    vectors = np.array(vectors, dtype='float32')
    dependant_vectors_index = []  # the index of vectors that are dependent
    orthonormal_basis = np.zeros(shape=vectors.shape, dtype='float32')  # Save orthonormal basis in this
    column_count = 0

    r_vector = np.zeros(shape=(vectors.shape[1], vectors.shape[1]), dtype='float32')  # Norms of \hat{q}

    for index, column in enumerate(vectors.T):
        ############## Your code here
        if index == 0:
            q_hat_norm = np.linalg.norm(column)
            orthonormal_basis.T[column_count] = column / q_hat_norm
            r_vector.T[0] = np.array([np.dot(column, orthonormal_basis.T[0]), 0, 0])
            column_count += 1

        else:
            q_hat = q_hat_calculate(index, column, orthonormal_basis)
            q_hat_norm = np.linalg.norm(q_hat)
            
            ##### Handle the dependant vectors: (Hint: use `epsilon` variable)
            if q_hat_norm > epsilon:
                orthonormal_basis.T[column_count] = q_hat / q_hat_norm
                column_count += 1
            else:
                dependant_vectors_index.append(index)
                
            for index_dep in dependant_vectors_index:
                r_vector[index_dep][index] = 0.0
            
            for i in range(index + 1):
                r_vector.T[index][i] = np.dot(column, orthonormal_basis.T[i])
                
        ###############

    print(f'the input vectors are:\n{vectors}')
    print(100 * '-')

    if column_count == vectors.shape[1]:  # all vectors were independent
        print(f'the vectors were linearly independent and orthonormal basis:\n{orthonormal_basis}')

    return orthonormal_basis, r_vector

In [4]:
vec = [[1, -1, 4],
       [1, 4, -2],
       [1, 4, 2],
       [1, -1, 0]]

Q, R = gram_schmidt_algorithm(vectors=vec)
print(f'Q=\n{Q}')
print(f'R=\n{R}')

the input vectors are:
[[ 1. -1.  4.]
 [ 1.  4. -2.]
 [ 1.  4.  2.]
 [ 1. -1.  0.]]
----------------------------------------------------------------------------------------------------
the vectors were linearly independent and orthonormal basis:
[[ 0.5 -0.5  0.5]
 [ 0.5  0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5]]
Q=
[[ 0.5 -0.5  0.5]
 [ 0.5  0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5]]
R=
[[ 2.  3.  2.]
 [ 0.  5. -2.]
 [ 0.  0.  4.]]


In [5]:
np.dot(Q, R) == vec   #q

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])